
[workspace]
name = "test-default"
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64"]

[tasks]
test = "python -c 'print(\"Hello world!\")'"

[dependencies]
python = "3.12.*"
rubin-env-rsp = "*"
